# Generated by Django 5.2.5 on 2025-08-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='clip',
            field=models.FileField(blank=True, null=True, upload_to='clips/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='snapshots/'),
        ),
    ]
