# Generated by Django 5.2.5 on 2025-08-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_clip_alter_alert_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
